title: Micropub Content
url: https://brianzelip.github.io/micropub-content
micropub_endpoint: https://bzelip-micropub-endpoint.glitch.me/micropub

permalink: /posts/:title
kramdown:
  hard_wrap: true
